branches:
  except:
    - /^feature.*$/

language: go

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -repotoken axbhu7krL0AQgXUB1eGFvuB53Cnm7rQix
  - go test -v .
